version: 2
tags: ["documentation"]
accept_configuration:
  condition: or
  conditions:
    - condition: property
      property: features
      contains_value: LicenseCheck
    - condition: and
      conditions:
        - condition: property
          property: target.os
          equals_value: "Linux"
        - condition: property
          property: configureArgs
          not_contains_value: "-DFEATURE_gui=OFF"

instructions:
  Build:
    - type: EnvironmentVariable
      variableName: BUILD_DOCUMENTATION
      variableValue: "1"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
